language: python
services:
  - docker
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- docker run -p 7474:7474 -p 7473:7473 -p 7687:7687 --env NEO4J_AUTH=neo4j/test -d neo4j:3.5
install:
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Y2+sT1vu4X2aelh7/Rwxwf/Mq479OwsVHqJ6I3lxGhDaiK0YXBVHM/kzdcjlvJQnUCMO3dHpW+MxT94XHXAoPBxXVdyhjebY/MqhhJ+Q9WpsSMM0Z/xemDEAVvhCTD8bJFwPZSIFl1SBr/IiZNHPVzZkGmZXryvz5/VXyXK1Nw4do+78aI3Ab0kR5/c6m6mRC5MQqs0pXcl7i1h3iR2Qm8z5IKqRZa7kamEzFfmuOen9JcVLiBkHV27f5vilf+yk9XIGZDDlYWZCF1U2yjHQpZHgIusWwhfsGXJefOXQbhafLyiqfdKnZnRAsgINDmfDzEig5cQQs1XFCcxo051PCpmYNm7qFpp/c+u6M9UtpN8oh2krWSEBK9Nf+UU+FWoJjhtNdO94kqpX8GPwK4LKuSJNSlmAk3NJMI5O520R7CAW/AnD4DLLcDWUjzoUypmSF3eGlsmxxgnSpKCohmOOP/HIwHAbLO8zGwTAZe2F7L1NKPlO5cRs9XI3cN4apRfWuwy+v3lyT2oaPSQXw1YCmoH5qX6uwtQfFmeCtvLu++qM5K/aZk8YuMCs2geNnJ9SjYlK+s7UisBKIwwAeDVdkOj+Te0f/Nb7wkkGF05+mYu2IN8/ccl7pwRjLG0vlWyu8oYShWb1ipM0c0Q+xeLkBzfE9tUg1UB5++btF+O/xlw="
  on:
    tags: true
  skip_existing: true
